project_id = "uohhfesyumigbpqjpacl"

[functions.subscribe-newsletter]
verify_jwt = false

[functions.fetch-blog-posts]
verify_jwt = false

[functions.fetch-blog-post]
verify_jwt = false

[functions.sync-lead-to-notion]
verify_jwt = false

[functions.fetch-notion-page]
verify_jwt = false

[functions.og-blog]
verify_jwt = false

[functions.enrich-fiction]
verify_jwt = false

[functions.celebrate-fiction]
verify_jwt = false
